### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by pyigyli** [stadibo/friseurManager#1]
### Positiivisia kommentteja

- Koodi yleisesti ottaen helposti seurattavaa ja ymmärrettävää.
- Hyvät kommentit tekivät tästä vielä helpompaa.
- Muuttujilla ja metodeilla hyvin kuvaavat nimet.
- Jaottelu kansioihin järkevä.
- Ihailin komentoa map(lamda ... ). Tämä oli minulle uutta, mutta nyt opin mitä tämä tekee.

### Virheitä

- Herokussa salasanaa ei tarkisteta admin-käyttäjälle. Voin kirjautua adminille tyhjällä tai millä tahansa muulla salasanalla. Tämä on kai virhe?
- Jos yritän luoda uuden käyttäjän tai kampaajan käyttäjänimellä, joka  on jo käytössä, saan virheen sqlalchemy.exc.IntegrityError: UNIQUE constraint failed. Kannattaa toteuttaa tälle tilanteelle käyttäjäystävällinen virheviesti.
- Muutamalla napilla on puuttuvia toimintoja, jotka varmasti toteutetaan tulevilla viikoilla. Toiseksi, tällä hetkellä roolien "FRISEUR" ja "USER" välillä ei ole mitään eroja, mutta sekin muuttuu varmasti myöhemmin.
- Poistaessa käyttäjää, häneen liittyvät tiedot muista tietokannoista eivät poistu. Kannattaa käydä kaikki poistamistoiminnot läpi, että poistettavaan riviin liittyvät tiedot poistuvat myös.

### Parannusehdotuksia

- Kun luo uuden käyttäjän, olisi mukavempi kirjautua samalla automaattisesti tällä käyttäjällä sisään.
- Kun kampaajan koko päivä on buukattu täyteen varatuilla ajoilla, olisi parempi, ettei tätä päivää voi enää valita, sillä käyttäjähän näkee vain tyhjän sivun.

**Comment by stadibo** [comment]
**Kiitos vielä palautteesta!** Oli muuten hyvä huomio tuon kirjautumistarkastuksen puuttuminen. Myös: 
- *Poistaessa käyttäjää, häneen liittyvät tiedot muista tietokannoista eivät poistu. Kannattaa käydä kaikki poistamistoiminnot läpi, että poistettavaan riviin liittyvät tiedot poistuvat myös.*

oli erittäin hyvä ehdotus/muistutus ja selvittelin sitä myöhemmin. 
**Onnea loppusuoralle!**
